services:
  whatsmiau:
    build: .
    container_name: whatsmiau
    ports:
      - "8081:8081"
    environment:
      - REDIS_URL=redis:6379
      - DB_URL=postgres://whatsmiau:123123123@localhost:5432/whatsmiau?sslmode=disable
    volumes:
      - whatsmeow:/app/data
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis-data:/data
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: postgres
    volumes:
      - pg-data:/pg-data
    restart: unless-stopped
    environment:
      POSTGRES_USER: whatsmiau
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: whatsmiau

volumes:
  redis-data:
    driver: local
  whatsmeow:
    driver: local
  pg-data:
    driver: local
